<div class="account">
    <div class="column main">
        <div class="block block-order-details">
            <div class="order-date">
                <?= __('Order Date: ') ?> <?= $block->formatDate($block->getOrder()->getCreatedAt(), \IntlDateFormatter::LONG) ?>
            </div>
            <div class="order-status">
                <?= /* @escapeNotVerified */ $block->getOrder()->getStatusLabel() ?>
            </div>
        </div>

        <?= $block->getChildHtml('order_view') ?>
        <?= $block->getChildHtml('info') ?>
    </div>
</div>
